planning_server_node:
  ros__parameters:
    WB: 3.0
    W: 2.0
    LF: 3.3  # distance from rear to vehicle front end
    LB: 1.0  # distance from rear to vehicle back end
    MAX_STEER: 0.6  # [rad] maximum steering angle
    BUBBLE_DIST: 1.15  # distance from rear to center of vehicle.
    BUBBLE_R: 2.0615528128088303  # bubble radius
    VRX: [3.3, 3.3, -1.0, -1.0, 3.3]  # vehicle rectangle vertices
    VRY: [1.0, -1.0, -1.0, 1.0, 1.0]  # vehicle rectangle vertices
    XY_GRID_RESOLUTION: 2.0  # [m]
    YAW_GRID_RESOLUTION: 0.2617993877991494  # [rad] (equivalent to np.deg2rad(15.0))
    MOTION_RESOLUTION: 0.1  # [m] path interpolate resolution
    N_STEER: 20  # number of steer command
    SB_COST: 100.0  # switch back penalty cost
    BACK_COST: 5.0  # backward penalty cost
    STEER_CHANGE_COST: 5.0  # steer angle change penalty cost
    STEER_COST: 1.0  # steer angle change penalty cost
    H_COST: 5.0  # Heuristic cost